version: '3.2'
services:
  redis:
    container_name: cluster-redis
    restart: unless-stopped
    image: redis
    ports:
      - '6379:6379'
  rabbitmq:
    container_name: cluster-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
